dist: bionic
language: ruby
script: bundle exec rake test
jobs:
  include:
    - rvm: 2.7
      gemfile: Gemfile
    - rvm: 2.6
      gemfile: test/gemfiles/actionmailer52.gemfile
    - rvm: 2.5
      gemfile: test/gemfiles/actionmailer51.gemfile
    - rvm: 2.4
      gemfile: test/gemfiles/actionmailer50.gemfile
    - rvm: 2.7
      gemfile: test/gemfiles/mongoid7.gemfile
      services:
        - mongodb
    - rvm: 2.6
      gemfile: test/gemfiles/mongoid6.gemfile
      services:
        - mongodb
notifications:
  email:
    on_success: never
    on_failure: change
